
version: '2.4'

services:
  rasa:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_srv.Dockerfile
    image: arcadia_rasa_server
    networks: ['rasa-network']
    ports:
      - "5005:5005"

  action_server:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_actions.Dockerfile
    image: arcadia_rasa_actions
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    links:
    - rasa

  arcadia:
    build:
      context: ./src
      dockerfile: dockerfiles/arcadia.Dockerfile
    image: arcadia_client
    volumes:
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - "/dev/snd:/dev/snd"
    networks: ['rasa-network']
    group_add:
      - audio
    links:
      - rasa

networks: {rasa-network: {}}