
version: '2.4'

networks:
  rasa-network:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 172.20.0.0/16

services:
  rasa:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_srv.Dockerfile
    image: arcadia_rasa_server
    networks: 
        rasa-network:
            ipv4_address: 172.20.0.2
    ports:
      - "5005:5005"

  action_server:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_actions.Dockerfile
    image: arcadia_rasa_actions
    networks:
        rasa-network:
            ipv4_address: 172.20.0.3
    ports:
    - "5055:5055"
    links:
    - rasa

  arcadia:
    build:
      context: ./src
      dockerfile: dockerfiles/arcadia.Dockerfile
    image: arcadia_client
    volumes:
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - "/dev/snd:/dev/snd"
    networks:
        rasa-network:
            ipv4_address: 172.20.0.4
    group_add:
      - audio
    links:
      - rasa
