
version: '2.4'

networks:
  rasa-network:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 172.20.0.0/16

services:
  rasa:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_srv.Dockerfile
    image: arcadia_rasa_server
    networks: 
        rasa-network:
            ipv4_address: 172.20.0.2
    ports:
      - "5005:5005"
    cpu_count: 2
    mem_limit: 4096M

  action_server:
    build: 
      context: ./src
      dockerfile: dockerfiles/rasa_actions.Dockerfile
    env_file:
      - src/chatbot/actions/.actions.env
    image: arcadia_rasa_actions
    networks:
        rasa-network:
            ipv4_address: 172.20.0.3
    ports:
    - "5055:5055"
    links:
    - rasa
    mem_limit: 2048M

  arcadia:
    build:
      context: ./src
      dockerfile: dockerfiles/arcadia.Dockerfile
    image: arcadia_client
    networks:
        rasa-network:
            ipv4_address: 172.20.0.4
    links:
      - rasa
    volumes:
      - audio:/code/test_files
    ports:
      - "8000:8000"
    mem_limit: 1024M

volumes:
  audio: