name: SSH - Conectarse, actualizar y volver a levantar Arcadia
on:
  push:
    branches:
      - arcadia-api
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Despliegue por SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ArcadiaVoiceAssistant
          make deploy